[workspace]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "osx-64", "win-64"]
name = "magiccube"
readme = "README.rst"
authors = ["David W. Hogg", "Jake Vanderplas", "Misagh Soltani"]
license = "GPL-2.0"
license-file = "LICENSE.txt"
channels = ["https://prefix.dev/conda-forge"]
preview = ["pixi-build"]

[dependencies]
python = ">=3.7"
numpy = ">=2.3.2,<3"
matplotlib = ">=3.10.5,<4"

[tasks]
magiccube = "python -m magiccube.cube_interactive"

[package]
name = "magiccube"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "*" }
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
]
configuration = { debug-dir = ".build-debug", extra-input-globs = ["*.rst"] }

[package.host-dependencies]
hatchling = ">=1.27.0,<2"
uv = "*"

[package.build-dependencies]
python = ">=3.7"

[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
build = { features = ["build"], solve-group = "default" }
all = { features = ["dev", "build"], solve-group = "default" }

[pypi-dependencies]
magiccube = { path = ".", editable = true }

[feature.dev.dependencies]
ruff = "*"
pyright = ">=1.1.403,<2"
mypy = ">=1.17.1,<2"

[feature.dev.tasks]
lint = "ruff check --fix"
ulint = "ruff check --fix --unsafe-fixes"
format = "ruff format"
fix = "ruff check --fix --unsafe-fixes; ruff format"

[feature.build.dependencies]
hatch = "*"

[feature.build.tasks]
build = "hatch build -t wheel -t sdist"
